[build]
  publish = "."

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 301

[[redirects]]
  from = "/gallery"
  to = "/gallery.html"
  status = 301
